name: GitHub Package Stable Release

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: release
  cancel-in-progress: true

env:
  DOTNET_VERSION: '9.0.x'
  FEED: "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
  TEMP_OUTPUT: "./nupkgs"

jobs:
  publish:
    name: Stable Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref || github.ref }}

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Feed
        run: |
          dotnet nuget add source "${{ env.FEED }}" \
            --username "${{ github.repository_owner }}" \
            --password "${{ secrets.GITHUB_TOKEN }}" \
            --store-password-in-clear-text \
            --name github

      - name: Restore
        run: dotnet restore ${{ vars.SOLUTION }}

      - name: Build
        run: dotnet build ${{ vars.SOLUTION }} --no-restore --configuration ${{ vars.CONFIGURATION }}

      - name: Pack
        run: |
          dotnet pack ${{ vars.SOLUTION }} --no-build --configuration ${{ vars.CONFIGURATION }} --output ${{ env.TEMP_OUTPUT }}

      - name: Publish
        run: |
          dotnet nuget push ${{ env.TEMP_OUTPUT }}/*.nupkg \
            --source github \
            --api-key "${{ secrets.GITHUB_TOKEN }}" \
            --skip-duplicate
        continue-on-error: true