name: Nightly Release

on:
    workflow_dispatch:
      
    schedule:
        - cron: '5 0 * * *'
          
permissions:
    contents: read
    packages: write
          
concurrency:
    group: nightly
    cancel-in-progress: true
    
env:
    DOTNET_VERSION: '9.0.x'

jobs:
    release:
        runs-on: ubuntu-latest
  
        steps:
            - name: Checkout
              uses: actions/checkout@v4
  
            - name: Setup
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
  
            - name: Restore
              run: dotnet restore ${{ vars.SOLUTION }}
  
            - name: Build
              run: dotnet build ${{ vars.SOLUTION }} --no-restore --configuration ${{ vars.CONFIGURATION }}
  
            - name: Pack
              run: dotnet pack ${{ vars.SOLUTION }} --no-build --configuration ${{ vars.CONFIGURATION }}
                
            - name: Source
              run: |
                dotnet nuget add source \
                  --username "${{ github.actor }}" \
                  --password "${{ secrets.GITHUB_TOKEN }}" \
                  --store-password-in-clear-text \
                  --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
  
            - name: Publish
              run: |
                dotnet nuget push **/bin/Release/*.nupkg \
                  --source github \
                  --api-key "${{ secrets.GITHUB_TOKEN }}" \
                  --skip-duplicate