name: NuGet Stable Release

on:
  workflow_dispatch:
    inputs: 
      git_ref:
        description: 'Git ref (tag or branch) to build'
        required: true
        default: 'main'
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: release
  cancel-in-progress: true

env:
  DOTNET_VERSION: '9.0.x'
  FEED: "https://api.nuget.org/v3/index.json"
  TEMP_OUTPUT: "./nupkgs"

jobs:
  publish:
    name: Stable Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.git_ref || github.ref }}

      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ vars.SOLUTION }}

      - name: Build
        run: dotnet build ${{ vars.SOLUTION }} --no-restore --configuration ${{ vars.CONFIGURATION }}

      - name: Pack
        run: |
          dotnet pack ${{ vars.SOLUTION }} --no-build --configuration ${{ vars.CONFIGURATION }} --output ${{ env.TEMP_OUTPUT }}

      - name: Publish
        run: |
          dotnet nuget push ${{ env.TEMP_OUTPUT }}/*.nupkg \
            --source ${{ env.FEED }} \
            --api-key "${{ secrets.NUGET_API_KEY }}"